# Generated by Django 2.0.5 on 2018-06-01 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180531_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='post',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='삭제일시'),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='부제목'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='댓글 내용입니다.', verbose_name='내용'),
        ),
    ]
